

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "MainPage.xaml.h"




void ::UnivWASAPIsynthTest::MainPage::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///MainPage.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///MainPage.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the TextBox named 'txtBox'
    txtBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"txtBox"));
    // Get the ToggleButton named 'tglBtn'
    tglBtn = safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"tglBtn"));
}

void ::UnivWASAPIsynthTest::MainPage::Connect(int connectionId, Platform::Object^ target)
{
    switch (connectionId)
    {
    case 1:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(target))->Checked +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::UnivWASAPIsynthTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::tglBtnChecked);
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(target))->Unchecked +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::UnivWASAPIsynthTest::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::tglBtnUnchecked);
        break;
    }
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

